backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "poetry"
    label: "詩與散文"
    folder: "content/poetry"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - { label: "分類", name: "category", widget: "select", options: ["詩", "散文"] }
      - { label: "封面圖", name: "thumbnail", widget: "image" }
      - { label: "內容", name: "body", widget: "markdown" }

  - name: "travel"
    label: "旅遊攝影"
    folder: "content/travel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - { label: "地點", name: "location", widget: "string" }
      - { label: "照片", name: "thumbnail", widget: "image" }
      - { label: "內文", name: "body", widget: "markdown" }